export const theme = {
  colors: {
    background: "#E5481C",
    backgroundSoft: "#F46A35",
    surface: "#FFF8F0",
    surfaceMuted: "#FFEBDD",
    surfaceStrong: "#FFFFFF",
    border: "#F4C6AD",
    text: "#B43614",
    textSoft: "#C56C4B",
    textMuted: "#D58D71",
    accent: "#FF6A00",
    accentDark: "#E85D00",
    accentSoft: "#FFD9BF",
    success: "#2E8A57",
    danger: "#C94A34",
    white: "#FFFFFF",
    overlay: "rgba(175, 58, 22, 0.18)",
  },
  radius: {
    sm: 12,
    md: 18,
    lg: 26,
    xl: 34,
    pill: 999,
  },
  spacing: {
    xs: 8,
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  shadow: {
    shadowColor: "#8F2B10",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 16,
    elevation: 7,
  },
  softShadow: {
    shadowColor: "#8F2B10",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
};
